version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: test-mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports: 
      - 3306:3306
    volumes:
      - ./code/mysql:/var/lib/mysql  
    networks:
      test-lemp-network:
        ipv4_address: 172.28.1.1


  webserver:
    build: 
      context: ./
      dockerfile: dockerfile
    image: test_nginx:latest
    container_name: test-webserver
    ports:
      - "80:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./code/nginxlog:/var/log/nginx
    networks:
      test-lemp-network:
        ipv4_address: 172.28.1.2

  php: 
    build: 
      context: ./
      dockerfile: dockerfile-phpfpm
    image: testphpfpm:latest  
    volumes: 
      - ./code:/code
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    container_name: test-phpfpm
    networks:
      test-lemp-network:
        ipv4_address: 172.28.1.3


networks: 
  test-lemp-network:
    ipam:
      driver: default
      config:
          - subnet: 172.28.0.0/16
